# Generated by Django 4.2.11 on 2025-11-15 09:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('phone_number', models.CharField(max_length=17)),
                ('transaction_type', models.CharField(choices=[('CONTRIBUTION', 'Member Contribution'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('FEE', 'Service Fee'), ('WITHDRAWAL', 'Chama Withdrawal')], default='CONTRIBUTION', max_length=20)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'STK Push Sent'), ('COMPLETED', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='core.chama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['phone_number'], name='daraja_mpes_phone_n_cff809_idx'), models.Index(fields=['mpesa_receipt_number'], name='daraja_mpes_mpesa_r_9349a7_idx'), models.Index(fields=['checkout_request_id'], name='daraja_mpes_checkou_876add_idx'), models.Index(fields=['status'], name='daraja_mpes_status_a0524e_idx'), models.Index(fields=['transaction_type'], name='daraja_mpes_transac_0ee906_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('merchant_request_id__isnull', False)), fields=('merchant_request_id',), name='unique_merchant_request_id'),
        ),
    ]
