# Generated by Django 4.2.11 on 2025-11-15 09:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chama',
                'verbose_name_plural': 'Chamas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_ref', models.CharField(blank=True, max_length=120)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InterestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Monthly interest rate in percent (e.g. 1.5 for 1.5%).', max_digits=5)),
                ('tenure_months', models.PositiveSmallIntegerField(default=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Repaid', 'Repaid'), ('Defaulted', 'Defaulted')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('national_id', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_ref', models.CharField(blank=True, max_length=120)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='api.loan')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distributed_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='api.chama')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.chama')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.member')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfitShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.profitdistribution')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membership')),
            ],
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='api_member_phone_179983_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['national_id'], name='api_member_nationa_7f1727_idx'),
        ),
        migrations.AddField(
            model_name='loan',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.membership'),
        ),
        migrations.AddField(
            model_name='interestentry',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_entries', to='api.loan'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='api.membership'),
        ),
        migrations.AddIndex(
            model_name='chama',
            index=models.Index(fields=['name'], name='api_chama_name_5f5cd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profitdistribution',
            unique_together={('chama', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('member', 'chama')},
        ),
        migrations.AlterUniqueTogether(
            name='memberprofitshare',
            unique_together={('distribution', 'membership')},
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='api_loan_status_bf8338_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['membership'], name='api_loan_members_b98fb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interestentry',
            unique_together={('loan', 'month')},
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['date'], name='api_contrib_date_465865_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['membership'], name='api_contrib_members_e084ec_idx'),
        ),
    ]
