# Generated by Django 4.2.11 on 2025-11-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('Contribution', 'Contribution'), ('Loan Repayment', 'Loan Repayment')], max_length=40)),
                ('checkout_request_id', models.CharField(blank=True, max_length=120, null=True)),
                ('mpesa_receipt', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(default='Pending', max_length=40)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='interestentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='interestentry',
            name='loan',
        ),
        migrations.AlterUniqueTogether(
            name='memberprofitshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='memberprofitshare',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='memberprofitshare',
            name='membership',
        ),
        migrations.AlterUniqueTogether(
            name='profitdistribution',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='chama',
        ),
        migrations.AlterModelOptions(
            name='chama',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chama',
            name='api_chama_name_5f5cd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='contribution',
            name='api_contrib_date_465865_idx',
        ),
        migrations.RemoveIndex(
            model_name='contribution',
            name='api_contrib_members_e084ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='api_loan_status_bf8338_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='api_loan_members_b98fb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='api_member_phone_179983_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='api_member_nationa_7f1727_idx',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='disbursed_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Repaid', 'Repaid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chama'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
        migrations.DeleteModel(
            name='InterestEntry',
        ),
        migrations.DeleteModel(
            name='MemberProfitShare',
        ),
        migrations.DeleteModel(
            name='ProfitDistribution',
        ),
    ]
