# Generated by Django 4.2.11 on 2025-11-16 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_member_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.chama'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.member'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Contribution', 'Contribution'), ('Loan Repayment', 'Loan Repayment')], default='Contribution', max_length=40),
        ),
        migrations.AddIndex(
            model_name='chama',
            index=models.Index(fields=['name'], name='api_chama_name_5f5cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='chama',
            index=models.Index(fields=['is_active'], name='api_chama_is_acti_c1d0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['membership'], name='api_contrib_members_e084ec_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['date'], name='api_contrib_date_465865_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['confirmed'], name='api_contrib_confirm_07d160_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['membership'], name='api_loan_members_b98fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='api_loan_status_bf8338_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['applied_at'], name='api_loan_applied_1dc0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='api_member_phone_179983_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['national_id'], name='api_member_nationa_7f1727_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_active'], name='api_member_is_acti_09353f_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['member', 'chama'], name='api_members_member__676736_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['is_admin'], name='api_members_is_admi_dc4db4_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['is_active'], name='api_members_is_acti_d462b9_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['phone'], name='api_mpesatr_phone_84673f_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['mpesa_receipt'], name='api_mpesatr_mpesa_r_953f42_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status'], name='api_mpesatr_status_735dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='api_mpesatr_checkou_958260_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['loan'], name='api_repayme_loan_id_8617ae_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['date'], name='api_repayme_date_6259e8_idx'),
        ),
    ]
