# Generated by Django 4.2.11 on 2025-11-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0001_initial'),
    ]

    operations = [
    ]
